[project]
name = "quantic-hr-ai-rag-group-project"
version = "0.1.0"
description = "Group project: AI RAG App for Human Resources"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4",
    "chromadb>=1.5.9",
    "fastembed>=0.8.1",
    "groq>=1.7.0",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "markdownify",
    "mcp>=2.2.0",
    "python-dotenv>=1.2.3",
    "rank-bm25>=0.2.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
